### ISSUE TITLE
Vite + Code Hike

### ISSUE THREAD

**Issue by ldalves** [code-hike/codehike#384]
Hi! 👋 

Trying to get the `examples/vite` from https://github.com/code-hike/codehike/tree/next/examples/vite up and got the following error after running the `yarn install` and `yarn dev`:

```
examples/vite git:(next) ▶ yarn dev
yarn run v1.22.19
$ vite
✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@code-hike/mdx". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/esbuild/lib/main.js:1365:27:
      1365 │         let result = await callback({
           ╵                            ^

    at packageEntryFailure (file:///Users/leandroalves/dev/codehike/examples/vite/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:21837:11)
    at resolvePackageEntry (file:///Users/leandroalves/dev/codehike/examples/vite/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:21834:5)
    at tryNodeResolve (file:///Users/leandroalves/dev/codehike/examples/vite/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:21572:20)
    at file:///Users/leandroalves/dev/codehike/examples/vite/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62039:40
    at requestCallbacks.on-resolve (/Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:1365:28)
    at handleRequest (/Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:727:19)
    at handleIncomingPacket (/Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:749:7)
    at Socket.readFromStdout (/Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:677:7)
    at Socket.emit (node:events:511:28)
    at addChunk (node:internal/streams/readable:332:12)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1287:20:
      1287 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/leandroalves/dev/codehike/examples/vite/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62028:27)
    at handlePlugins (/Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:1287:21)
    at buildOrServeImpl (/Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:974:5)
    at Object.buildOrServe (/Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:780:5)
    at /Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:2132:17
    at new Promise (<anonymous>)
    at Object.build (/Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:2131:14)
    at build (/Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:1978:51)
    at bundleConfigFile (file:///Users/leandroalves/dev/codehike/examples/vite/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:61992:26)

  The plugin "externalize-deps" was triggered by this import

    vite.config.js:3:31:
      3 │ import { remarkCodeHike } from "@code-hike/mdx"
        ╵                                ~~~~~~~~~~~~~~~~

failed to load config from /Users/leandroalves/dev/codehike/examples/vite/vite.config.js
error when starting dev server:
Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:1365:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@code-hike/mdx". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:1604:15)
    at /Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:1056:28
    at runOnEndCallbacks (/Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:1476:61)
    at buildResponseToResult (/Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:1054:7)
    at /Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:1166:14
    at responseCallbacks.<computed> (/Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:701:9)
    at handleIncomingPacket (/Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:756:9)
    at Socket.readFromStdout (/Users/leandroalves/dev/codehike/examples/vite/node_modules/esbuild/lib/main.js:677:7)
    at Socket.emit (node:events:511:28)
    at addChunk (node:internal/streams/readable:332:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Am missing something?  

Thanks in advance!

Leandro

**Comment by ldalves** [comment]
I checked that it works in [stackblitz](https://stackblitz.com/github/code-hike/codehike/tree/main/examples/vite?file=src%2Fhello.mdx). And the configuration looks the same to me.

Yes. I'm trying from within the cod-hike repo.

Hmm I can try that, but since all the dependencies are in the package.json, I was expecting this to work. :)
